# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/codrin/Downloads/clion-2026.1.1/bin/cmake/linux/x64/bin/cmake

# The command to remove a file.
RM = /home/codrin/Downloads/clion-2026.1.1/bin/cmake/linux/x64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/codrin/Marat/AppLagCPU

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/codrin/Marat/AppLagCPU

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/home/codrin/Downloads/clion-2026.1.1/bin/cmake/linux/x64/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/codrin/Downloads/clion-2026.1.1/bin/cmake/linux/x64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/codrin/Marat/AppLagCPU/CMakeFiles /home/codrin/Marat/AppLagCPU//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/codrin/Marat/AppLagCPU/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/codrin/Marat/AppLagCPU/CMakeFiles /home/codrin/Marat/AppLagCPU//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/codrin/Marat/AppLagCPU/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named amd_applag

# Build rule for target.
amd_applag: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 amd_applag
.PHONY : amd_applag

# fast build rule for target.
amd_applag/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amd_applag.dir/build.make CMakeFiles/amd_applag.dir/build
.PHONY : amd_applag/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amd_applag.dir/build.make CMakeFiles/amd_applag.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amd_applag.dir/build.make CMakeFiles/amd_applag.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amd_applag.dir/build.make CMakeFiles/amd_applag.dir/main.cpp.s
.PHONY : main.cpp.s

src/CodeMem/CodeMem.o: src/CodeMem/CodeMem.cpp.o
.PHONY : src/CodeMem/CodeMem.o

# target to build an object file
src/CodeMem/CodeMem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amd_applag.dir/build.make CMakeFiles/amd_applag.dir/src/CodeMem/CodeMem.cpp.o
.PHONY : src/CodeMem/CodeMem.cpp.o

src/CodeMem/CodeMem.i: src/CodeMem/CodeMem.cpp.i
.PHONY : src/CodeMem/CodeMem.i

# target to preprocess a source file
src/CodeMem/CodeMem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amd_applag.dir/build.make CMakeFiles/amd_applag.dir/src/CodeMem/CodeMem.cpp.i
.PHONY : src/CodeMem/CodeMem.cpp.i

src/CodeMem/CodeMem.s: src/CodeMem/CodeMem.cpp.s
.PHONY : src/CodeMem/CodeMem.s

# target to generate assembly for a file
src/CodeMem/CodeMem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amd_applag.dir/build.make CMakeFiles/amd_applag.dir/src/CodeMem/CodeMem.cpp.s
.PHONY : src/CodeMem/CodeMem.cpp.s

src/Memory/memory.o: src/Memory/memory.cpp.o
.PHONY : src/Memory/memory.o

# target to build an object file
src/Memory/memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amd_applag.dir/build.make CMakeFiles/amd_applag.dir/src/Memory/memory.cpp.o
.PHONY : src/Memory/memory.cpp.o

src/Memory/memory.i: src/Memory/memory.cpp.i
.PHONY : src/Memory/memory.i

# target to preprocess a source file
src/Memory/memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amd_applag.dir/build.make CMakeFiles/amd_applag.dir/src/Memory/memory.cpp.i
.PHONY : src/Memory/memory.cpp.i

src/Memory/memory.s: src/Memory/memory.cpp.s
.PHONY : src/Memory/memory.s

# target to generate assembly for a file
src/Memory/memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amd_applag.dir/build.make CMakeFiles/amd_applag.dir/src/Memory/memory.cpp.s
.PHONY : src/Memory/memory.cpp.s

src/Registers/RegisterBank.o: src/Registers/RegisterBank.cpp.o
.PHONY : src/Registers/RegisterBank.o

# target to build an object file
src/Registers/RegisterBank.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amd_applag.dir/build.make CMakeFiles/amd_applag.dir/src/Registers/RegisterBank.cpp.o
.PHONY : src/Registers/RegisterBank.cpp.o

src/Registers/RegisterBank.i: src/Registers/RegisterBank.cpp.i
.PHONY : src/Registers/RegisterBank.i

# target to preprocess a source file
src/Registers/RegisterBank.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amd_applag.dir/build.make CMakeFiles/amd_applag.dir/src/Registers/RegisterBank.cpp.i
.PHONY : src/Registers/RegisterBank.cpp.i

src/Registers/RegisterBank.s: src/Registers/RegisterBank.cpp.s
.PHONY : src/Registers/RegisterBank.s

# target to generate assembly for a file
src/Registers/RegisterBank.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amd_applag.dir/build.make CMakeFiles/amd_applag.dir/src/Registers/RegisterBank.cpp.s
.PHONY : src/Registers/RegisterBank.cpp.s

src/Timing/Timing.o: src/Timing/Timing.cpp.o
.PHONY : src/Timing/Timing.o

# target to build an object file
src/Timing/Timing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amd_applag.dir/build.make CMakeFiles/amd_applag.dir/src/Timing/Timing.cpp.o
.PHONY : src/Timing/Timing.cpp.o

src/Timing/Timing.i: src/Timing/Timing.cpp.i
.PHONY : src/Timing/Timing.i

# target to preprocess a source file
src/Timing/Timing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amd_applag.dir/build.make CMakeFiles/amd_applag.dir/src/Timing/Timing.cpp.i
.PHONY : src/Timing/Timing.cpp.i

src/Timing/Timing.s: src/Timing/Timing.cpp.s
.PHONY : src/Timing/Timing.s

# target to generate assembly for a file
src/Timing/Timing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amd_applag.dir/build.make CMakeFiles/amd_applag.dir/src/Timing/Timing.cpp.s
.PHONY : src/Timing/Timing.cpp.s

src/cpu/Data/Execute/Alu.o: src/cpu/Data/Execute/Alu.cpp.o
.PHONY : src/cpu/Data/Execute/Alu.o

# target to build an object file
src/cpu/Data/Execute/Alu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amd_applag.dir/build.make CMakeFiles/amd_applag.dir/src/cpu/Data/Execute/Alu.cpp.o
.PHONY : src/cpu/Data/Execute/Alu.cpp.o

src/cpu/Data/Execute/Alu.i: src/cpu/Data/Execute/Alu.cpp.i
.PHONY : src/cpu/Data/Execute/Alu.i

# target to preprocess a source file
src/cpu/Data/Execute/Alu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amd_applag.dir/build.make CMakeFiles/amd_applag.dir/src/cpu/Data/Execute/Alu.cpp.i
.PHONY : src/cpu/Data/Execute/Alu.cpp.i

src/cpu/Data/Execute/Alu.s: src/cpu/Data/Execute/Alu.cpp.s
.PHONY : src/cpu/Data/Execute/Alu.s

# target to generate assembly for a file
src/cpu/Data/Execute/Alu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amd_applag.dir/build.make CMakeFiles/amd_applag.dir/src/cpu/Data/Execute/Alu.cpp.s
.PHONY : src/cpu/Data/Execute/Alu.cpp.s

src/cpu/Data/Execute/Execute.o: src/cpu/Data/Execute/Execute.cpp.o
.PHONY : src/cpu/Data/Execute/Execute.o

# target to build an object file
src/cpu/Data/Execute/Execute.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amd_applag.dir/build.make CMakeFiles/amd_applag.dir/src/cpu/Data/Execute/Execute.cpp.o
.PHONY : src/cpu/Data/Execute/Execute.cpp.o

src/cpu/Data/Execute/Execute.i: src/cpu/Data/Execute/Execute.cpp.i
.PHONY : src/cpu/Data/Execute/Execute.i

# target to preprocess a source file
src/cpu/Data/Execute/Execute.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amd_applag.dir/build.make CMakeFiles/amd_applag.dir/src/cpu/Data/Execute/Execute.cpp.i
.PHONY : src/cpu/Data/Execute/Execute.cpp.i

src/cpu/Data/Execute/Execute.s: src/cpu/Data/Execute/Execute.cpp.s
.PHONY : src/cpu/Data/Execute/Execute.s

# target to generate assembly for a file
src/cpu/Data/Execute/Execute.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amd_applag.dir/build.make CMakeFiles/amd_applag.dir/src/cpu/Data/Execute/Execute.cpp.s
.PHONY : src/cpu/Data/Execute/Execute.cpp.s

src/cpu/Decoder/Decoder.o: src/cpu/Decoder/Decoder.cpp.o
.PHONY : src/cpu/Decoder/Decoder.o

# target to build an object file
src/cpu/Decoder/Decoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amd_applag.dir/build.make CMakeFiles/amd_applag.dir/src/cpu/Decoder/Decoder.cpp.o
.PHONY : src/cpu/Decoder/Decoder.cpp.o

src/cpu/Decoder/Decoder.i: src/cpu/Decoder/Decoder.cpp.i
.PHONY : src/cpu/Decoder/Decoder.i

# target to preprocess a source file
src/cpu/Decoder/Decoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amd_applag.dir/build.make CMakeFiles/amd_applag.dir/src/cpu/Decoder/Decoder.cpp.i
.PHONY : src/cpu/Decoder/Decoder.cpp.i

src/cpu/Decoder/Decoder.s: src/cpu/Decoder/Decoder.cpp.s
.PHONY : src/cpu/Decoder/Decoder.s

# target to generate assembly for a file
src/cpu/Decoder/Decoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amd_applag.dir/build.make CMakeFiles/amd_applag.dir/src/cpu/Decoder/Decoder.cpp.s
.PHONY : src/cpu/Decoder/Decoder.cpp.s

src/cpu/cpu.o: src/cpu/cpu.cpp.o
.PHONY : src/cpu/cpu.o

# target to build an object file
src/cpu/cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amd_applag.dir/build.make CMakeFiles/amd_applag.dir/src/cpu/cpu.cpp.o
.PHONY : src/cpu/cpu.cpp.o

src/cpu/cpu.i: src/cpu/cpu.cpp.i
.PHONY : src/cpu/cpu.i

# target to preprocess a source file
src/cpu/cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amd_applag.dir/build.make CMakeFiles/amd_applag.dir/src/cpu/cpu.cpp.i
.PHONY : src/cpu/cpu.cpp.i

src/cpu/cpu.s: src/cpu/cpu.cpp.s
.PHONY : src/cpu/cpu.s

# target to generate assembly for a file
src/cpu/cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amd_applag.dir/build.make CMakeFiles/amd_applag.dir/src/cpu/cpu.cpp.s
.PHONY : src/cpu/cpu.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... amd_applag"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/CodeMem/CodeMem.o"
	@echo "... src/CodeMem/CodeMem.i"
	@echo "... src/CodeMem/CodeMem.s"
	@echo "... src/Memory/memory.o"
	@echo "... src/Memory/memory.i"
	@echo "... src/Memory/memory.s"
	@echo "... src/Registers/RegisterBank.o"
	@echo "... src/Registers/RegisterBank.i"
	@echo "... src/Registers/RegisterBank.s"
	@echo "... src/Timing/Timing.o"
	@echo "... src/Timing/Timing.i"
	@echo "... src/Timing/Timing.s"
	@echo "... src/cpu/Data/Execute/Alu.o"
	@echo "... src/cpu/Data/Execute/Alu.i"
	@echo "... src/cpu/Data/Execute/Alu.s"
	@echo "... src/cpu/Data/Execute/Execute.o"
	@echo "... src/cpu/Data/Execute/Execute.i"
	@echo "... src/cpu/Data/Execute/Execute.s"
	@echo "... src/cpu/Decoder/Decoder.o"
	@echo "... src/cpu/Decoder/Decoder.i"
	@echo "... src/cpu/Decoder/Decoder.s"
	@echo "... src/cpu/cpu.o"
	@echo "... src/cpu/cpu.i"
	@echo "... src/cpu/cpu.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

